# -*- coding: utf-8 -*-
"""SD-HD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkuFGoPF9eBDYeGQMEFmlHbyZvZO6avx
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import os

def video_to_jpg(video_path, output_folder, output_txt_path):

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)


    cap = cv2.VideoCapture(video_path)# Open the video file
    if not cap.isOpened():
        print("Error: Unable to open video file.")
        return

    frame_names = []
    frame_count = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break


        frame_name = f"frame_{frame_count:04d}.jpg" # Save frame as a JPEG image
        output_path = os.path.join(output_folder, frame_name)
        cv2.imwrite(output_path, frame)


        frame_names.append(frame_name) # Save frame name to the list

        frame_count += 1

    cap.release()


    with open(output_txt_path, 'w') as f: # Save frame names to a text file
        for name in frame_names:
            f.write("%s\n" % name)


video_path = "/content/drive/MyDrive/Devi_Stuti_sd.mp4"  # Path to the input video
output_folder = "/content/drive/MyDrive/output_sd_frames"  # Output folder to save JPEG frames
output_txt_path = "/content/drive/MyDrive/frames_sd_list.txt"  # Path to save the frame names text file

video_to_jpg(video_path, output_folder, output_txt_path)

# HD videos to frame conversions

import numpy as np

def video(video_path,output_path, output_txt_path):

    cap = cv2.VideoCapture(video_path)# Open the video file
    if not cap.isOpened():
        print("Error: Unable to open video file.")
        return

    frames = []
    frame_names = []
    frame_count = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break


        frame_name = f"frame_{frame_count:04d}.jpg"
        output_path = os.path.join(output_folder, frame_name)
        cv2.imwrite(output_path, frame)


        frame_names.append(frame_name) # Save frame names to a text file

        frame_count += 1

    cap.release()


    with open(output_txt_path, 'w') as f:
        for name in frame_names:
            f.write("%s\n" % name)

video_path = "/content/drive/MyDrive/Devi_Stuti_Hd.mp4"  # Path to the input video
output_path = "/content/drive/MyDrive/output_hd_frames"  # Path to save the output folder name
output_txt_path = "/content/drive/MyDrive/frames_hd_list.txt"  # Path to save the frame names text file

video(video_path, output_path,output_txt_path)


output_dir = '/content/data/VideoFrames'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)


video_stream = cv2.VideoCapture('/content/Devi_Stuti_sd.mp4')

#  FPS of the video
fps = video_stream.get(cv2.CAP_PROP_FPS)

#  to write frame filenames to a text file
frame_list_filename = os.path.join(output_dir, "/content/frame_SD_names.txt")
with open(frame_list_filename, 'w') as frame_list_file:

    frame_idx = 0
    while video_stream.isOpened():
        ret, frame = video_stream.read()
        if not ret:
            break


        if frame_idx % (fps / 20) == 0:# Save every frame that corresponds to 20 FPS
            frame_filename = f"frame_{frame_idx}.jpg"
            full_frame_path = os.path.join(output_dir,frame_filename)
            cv2.imwrite(full_frame_path, frame)
            frame_list_file.write(frame_filename + '\n')

        frame_idx += 1

# Release video stream
video_stream.release()